---

- name: Check if ipv6 are disabled
  command: "cat /etc/default/grub"
  register: checkmyconf

- name: Disable IPv6
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="'
    replace: 'GRUB_CMDLINE_LINUX="ipv6.disable=1 '
    backup: yes
  when: "'ipv6.disable=1' not in checkmyconf.stdout"

- name: Disable IPv6 | Apply changes 
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: "'ipv6.disable=1' not in checkmyconf.stdout"

- name: Show /etc/default/grup contains
  debug: msg="{{ checkmyconf.stdout }}"