---

#Module replace adds string each time. We have to change to module lineinfile

#- name: Check if ipv6 are disabled
#  command: grep -Fxq "ipv6.disable=1" /etc/default/grub
#  register: checkmyconf
#  ignore_errors: True
#  changed_when: False

- name: Check if ipv6 are disabled
    shell: "cat /etc/default/grub"
    register: checkmyconf

- name: a task that only happens if the user exists
    when: checkmyconf.stdout.find('ipv6.disable=1) != -1
    debug: msg="user hillsy exists"


- name: Disable IPv6
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="'
    replace: 'GRUB_CMDLINE_LINUX="ipv6.disable=1 '
    backup: yes
  when: checkmyconf.rc == 1

- name: Disable IPv6 | Apply changes 
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg


- name: Greet the world if /tmp/my.conf contains "127.0.0.1"
  debug: msg="Hello, world!"
  when: checkmyconf.rc == 0