---

- name: Disable IPv6
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    insertbefore: 'GRUB_CMDLINE_LINUX="'
    line: 'ipv6.disable=1 '
    backup: yes

- name: Disable IPv6 | Apply changes 
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg

#