---

- name: Disable IPv6
  lineinfile:
    dest=/etc/default/grub
    regexp='^GRUB_CMDLINE_LINUX='
    insertbefore=BOF
    line='GRUB_CMDLINE_LINUX="ipv6.disable=1 crashkernel=auto rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rhgb quiet"'

- name: Disable IPv6 | Apply changes 
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
