---

- name: Disable IPv6
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="'
    replace: 'GRUB_CMDLINE_LINUX="ipv6.disable=1 '
    backup: yes

- name: Disable IPv6 | Apply changes 
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg