---

- name: Disable SELinux
  lineinfile: 
    dest=/etc/selinux/config
    regexp=^SELINUX=
    line=SELINUX=disabled
#  shell: systemctl stop firewalld
#  shell: systemctl disable firewalld  

- name: Disable and stop firewall
  service:
    name=firewalld
    state=stopped
    enabled=no

