---

- name: Ensure login banner files are in place
  template: 
    src=login_banner.j2
    dest=/etc/issue.net


#- name: Ensure sshd settings are applied
#  lineinfile: 
#    dest=/etc/ssh/sshd_config
#    regexp=^{{ item.setting }}
#    line= "{{ item.setting }} {{ item.value }}"
#    state= {{ item.state }}
#  with_items: ssh_options


- name: restart sshd
  service: 
     name=sshd 
     state=restarted



