---

- name: Install NTP packages
  yum: 
    name=ntp 
    state=present

- name: Restart ntpd service and make it to start automatically on every reboot
  service:
    name=ntpd
    state=restarted
    enabled=yes

