---

- debug: var=ansible_date_time

- name: Send telegram notification
  telegram:
     token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
     chat_id: '6343788'
     msg: "[{{ ansible_hostname }}] configurated by common role at {{ ansible_date_time.date }} {{ ansible_date_time.time }}"