---

 - name: Send telegram notification
   telegram:
      token: "bot304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8"
      chat_id: 6343788
      msg: "[{{ ansible_hostname }}] configurated by common role at {{ ansible_facts.ansible_date_time.date }}"