---

- include: 01-base-packages.yml
  tags: packages

- include: 02-hostname.yml
  tags: hostname

- include: 03-banner.yml
  tags: banner

- include: 04-environment.yml
  tags: environment

- include: 05-disable_firewall_selinux.yml
  tags: selinux

#- include: 10-disable_ipv6.yml 
#  tags: ipv6

#- include: 11-disable_firewall_selinux.yml 
#  tags: selinux

