---

    - name: disable ipv6 mod
      file:
        path=/etc/modprobe.d/ipv6.conf
        state=touch
      when: ansible_os_family == 'RedHat'

    - name: ensure ipv6 module is disabled
      lineinfile:
        dest=/etc/modprobe.d/ipv6.conf
        line="options ipv6 disable=1"
      when: ansible_os_family == 'RedHat'

    - name: disable ipv6 networking
      lineinfile:
        dest=/etc/sysconfig/network
        line="NETWORKING_IPV6=no"
      when: ansible_os_family == 'RedHat'

    - name: Set sysctl parameters
      sysctl:
        name={{ item }}
        value=1
        sysctl_set=yes
        state=present
        reload=yes
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
      when: ansible_os_family == 'RedHat'
